#!/usr/bin/env Rscript
# ============================================================================
# pymmeans JSS case-study reference generator (comprehensive)
# ============================================================================
# Generates ALL R-side reference values used by jss_case_study.ipynb, into
# cs_ref/*.csv, so the case-study notebook is a self-contained, reproducible
# artifact. Every synthetic dataset is generated HERE (seeded) and written to
# CSV; the Python side reads identical data so the two engines fit the same
# numbers, not merely similar ones. emmeans benchmark datasets (pigs, oranges,
# neuralgia, fiber) are exported verbatim.
#
# Required R packages: emmeans, estimability, lme4, lmerTest, pbkrtest, car.
# Re-run to re-baseline; committed CSVs let the notebook run without R.
# ============================================================================

suppressMessages({
  library(emmeans)
  library(estimability)
  ok_mixed <- requireNamespace("lme4", quietly = TRUE) &&
    requireNamespace("lmerTest", quietly = TRUE) &&
    requireNamespace("pbkrtest", quietly = TRUE)
  if (ok_mixed) { library(lme4); library(lmerTest); library(pbkrtest) }
  ok_car <- requireNamespace("car", quietly = TRUE)
  if (ok_car) library(car)
})

args <- commandArgs(trailingOnly = FALSE)
script_arg <- grep("^--file=", args, value = TRUE)
BASE <- if (length(script_arg) > 0) {
  normalizePath(dirname(sub("^--file=", "", script_arg)))
} else normalizePath(".")
OUT <- file.path(BASE, "cs_ref")
dir.create(OUT, showWarnings = FALSE)
p <- function(f) file.path(OUT, f)
emm_sum <- function(em) as.data.frame(summary(em))

# wcsv() — write a data.frame to CSV with FULL float64 precision. R's
# write.csv() serialises doubles at ~15 significant digits, which does NOT
# round-trip an IEEE-754 double (17 are required). The Python side would then
# parse SLIGHTLY different doubles than R fit on, injecting a spurious ~1e-15
# disagreement into otherwise-deterministic comparisons. formatC(., 17, "g")
# emits the exact shortest-round-tripping representation, so pandas reconstructs
# the identical bit pattern. (The residual ~1e-14 that remains is purely the
# difference between R's and NumPy's linear-algebra routines — irreducible and
# expected, NOT a data-serialisation artefact.)
wcsv <- function(df, file) {
  df[] <- lapply(df, function(col)
    if (is.numeric(col)) trimws(formatC(col, digits = 17, format = "g")) else col)
  write.csv(df, file, row.names = FALSE)
}
cat("Writing case-study references to:", OUT, "\n")

# Capture EVERY R package whose output is cross-validated anywhere in the
# notebook — including the §XI specialised-class references (survey, ordinal,
# nnet) generated by the sibling scripts in ../../tests/r_reference and the
# survival (Cox) reference generated below — so the manifest is a complete,
# reproducible provenance record, not just the core toolchain.
ref_pkgs <- c("emmeans", "estimability", "lme4", "lmerTest", "pbkrtest",
              "car", "survival", "survey", "ordinal", "nnet", "multcomp")
present <- ref_pkgs[vapply(ref_pkgs, requireNamespace, logical(1),
                           quietly = TRUE)]
wcsv(data.frame(
  package = c("R", present),
  version = c(paste(R.version$major, R.version$minor, sep = "."),
              vapply(present, function(pk) as.character(packageVersion(pk)),
                     character(1)))
), p("versions.csv"))

# ===========================================================================
# SECTION I — Core algebra: grid alignment, L-matrix, EMM across model families
# ===========================================================================
set.seed(101)
n <- 300
d1 <- data.frame(
  A = factor(sample(c("a", "b", "c"), n, replace = TRUE)),
  B = factor(sample(c("p", "q"), n, replace = TRUE)),
  x = rnorm(n)
)
eta1 <- 0.4 + (d1$A == "b") * 0.7 + (d1$A == "c") * 1.3 +
  (d1$B == "q") * 0.5 + 0.6 * d1$x
d1$y      <- eta1 + rnorm(n, sd = 0.8)                # gaussian
d1$ybin   <- rbinom(n, 1, plogis(eta1 - 0.4))         # logistic
d1$ycount <- rpois(n, exp(0.2 + 0.3 * (d1$A == "c") + 0.4 * d1$x))  # poisson
d1$ypos   <- rgamma(n, shape = 2, rate = exp(-(0.5 + 0.3 * (d1$B == "q"))))
wcsv(d1, p("core_data.csv"))

# OLS: EMM of A + L matrix + reference grid
fit_ols <- lm(y ~ A + B + x, data = d1)
emA <- emmeans(fit_ols, ~ A)
sA <- emm_sum(emA)
wcsv(data.frame(A = sA$A, emmean = sA$emmean, SE = sA$SE, df = sA$df,
                     lower = sA$lower.CL, upper = sA$upper.CL),
          p("core_ols_emm_A.csv"))
L <- emA@linfct; colnames(L) <- names(coef(fit_ols))
wcsv(as.data.frame(L), p("core_ols_Lmatrix.csv"))
wcsv(as.data.frame(ref_grid(fit_ols)@grid), p("core_ols_refgrid.csv"))

# OLS by-group: A | B + pairs
emAB <- emmeans(fit_ols, ~ A | B)
sAB <- emm_sum(emAB)
wcsv(data.frame(A = sAB$A, B = sAB$B, emmean = sAB$emmean, SE = sAB$SE),
          p("core_ols_emm_A_by_B.csv"))

# joint_tests(): the omnibus Type-III-style F-test per model term (df1, df2,
# F-ratio, p). The factor-level F-test a reviewer expects alongside the EMMs.
jt <- as.data.frame(joint_tests(fit_ols))
wcsv(data.frame(term = jt[["model term"]], df1 = jt$df1, df2 = jt$df2,
                F_ratio = jt$F.ratio, p_value = jt$p.value),
     p("joint_tests_ols.csv"))

# Logistic GLM: link + response
fit_logit <- glm(ybin ~ A + B + x, data = d1, family = binomial())
sL <- emm_sum(emmeans(fit_logit, ~ A))
wcsv(data.frame(A = sL$A, emmean = sL$emmean, SE = sL$SE,
                     lower = sL$asymp.LCL, upper = sL$asymp.UCL),
          p("core_logit_emm_link.csv"))
sLr <- emm_sum(emmeans(fit_logit, ~ A, type = "response"))
wcsv(data.frame(A = sLr$A, prob = sLr$prob, SE = sLr$SE,
                     lower = sLr$asymp.LCL, upper = sLr$asymp.UCL),
          p("core_logit_emm_response.csv"))

# Poisson GLM: response (rate) + rate-ratio pairs
fit_pois <- glm(ycount ~ A + x, data = d1, family = poisson())
sPr <- emm_sum(emmeans(fit_pois, ~ A, type = "response"))
wcsv(data.frame(A = sPr$A, rate = sPr$rate, SE = sPr$SE),
          p("core_poisson_emm_response.csv"))
sPp <- emm_sum(summary(contrast(emmeans(fit_pois, ~ A), method = "pairwise"),
                       type = "response", adjust = "none"))
wcsv(data.frame(contrast = sPp$contrast, ratio = sPp$ratio, SE = sPp$SE,
                     p = sPp$p.value),
          p("core_poisson_pairs_ratio.csv"))

# Gamma GLM (log link): response
fit_gam <- glm(ypos ~ B + x, data = d1, family = Gamma(link = "log"))
sG <- emm_sum(emmeans(fit_gam, ~ B, type = "response"))
wcsv(data.frame(B = sG$B, response = sG$response, SE = sG$SE),
          p("core_gamma_emm_response.csv"))
cat("SECTION I done\n")

# ===========================================================================
# SECTION II — Estimability (rank-deficient / empty cell)
# ===========================================================================
set.seed(202)
combos <- expand.grid(g = c("a", "b", "c"), h = c("x", "y", "z"))
combos <- combos[!(combos$g == "c" & combos$h == "z"), ]
rows <- combos[rep(seq_len(nrow(combos)), each = 12), ]
rows$g <- factor(rows$g, levels = c("a", "b", "c"))
rows$h <- factor(rows$h, levels = c("x", "y", "z"))
rows$y <- rnorm(nrow(rows)) + as.integer(rows$g) * 0.3
wcsv(rows, p("estim_data.csv"))
fit_e <- lm(y ~ g * h, data = rows)
se <- emm_sum(emmeans(fit_e, ~ g * h))
se$nonEst <- is.na(se$emmean) | is.nan(se$emmean)
wcsv(data.frame(g = se$g, h = se$h, emmean = se$emmean, SE = se$SE,
                     nonEst = se$nonEst), p("estim_emm.csv"))
cat("SECTION II done — nonEst:", sum(se$nonEst), "\n")

# ===========================================================================
# SECTION III — Transformations (benchmark data)
# ===========================================================================
data(pigs)
wcsv(pigs, p("pigs_data.csv"))
pigs.lm <- lm(log(conc) ~ source + factor(percent), data = pigs)
spl <- emm_sum(emmeans(pigs.lm, ~ source))
wcsv(data.frame(source = spl$source, emmean = spl$emmean, SE = spl$SE,
                     df = spl$df, lower = spl$lower.CL, upper = spl$upper.CL),
          p("pigs_emm_link.csv"))
spr <- emm_sum(emmeans(pigs.lm, ~ source, type = "response"))
wcsv(data.frame(source = spr$source, response = spr$response, SE = spr$SE,
                     lower = spr$lower.CL, upper = spr$upper.CL),
          p("pigs_emm_response.csv"))
# Bias-adjusted back-transform: under log-normal residuals the response-scale
# mean is exp(eta + sigma^2/2), NOT exp(eta). emmeans applies this with
# bias.adj=TRUE + sigma; we write sigma so the Python side uses the identical
# value rather than re-estimating it.
sigma_pigs <- sigma(pigs.lm)
sba <- emm_sum(emmeans(pigs.lm, ~ source, type = "response",
                       bias.adj = TRUE, sigma = sigma_pigs))
wcsv(data.frame(source = sba$source, response = sba$response, SE = sba$SE,
                sigma = sigma_pigs), p("pigs_emm_response_biasadj.csv"))
# log-scale pairwise -> ratio (back-transform of a difference)
spp <- emm_sum(summary(contrast(emmeans(pigs.lm, ~ source), "pairwise"),
                       type = "response", adjust = "none"))
wcsv(data.frame(contrast = spp$contrast, ratio = spp$ratio, SE = spp$SE),
          p("pigs_pairs_ratio.csv"))

data(neuralgia)
wcsv(neuralgia, p("neuralgia_data.csv"))
neur.glm <- glm(Pain ~ Treatment + Sex + Age, data = neuralgia,
                family = binomial())
snr <- emm_sum(emmeans(neur.glm, ~ Treatment, type = "response"))
wcsv(data.frame(Treatment = snr$Treatment, prob = snr$prob, SE = snr$SE,
                     lower = snr$asymp.LCL, upper = snr$asymp.UCL),
          p("neuralgia_emm_response.csv"))
cat("SECTION III done\n")

# ===========================================================================
# SECTION IV — Trends + contrast families
# ===========================================================================
data(oranges)
wcsv(oranges, p("oranges_data.csv"))
org.lm <- lm(sales1 ~ price1 * day, data = oranges)
st <- emm_sum(emtrends(org.lm, ~ day, var = "price1"))
wcsv(data.frame(day = st$day, trend = st$price1.trend, SE = st$SE,
                     df = st$df, lower = st$lower.CL, upper = st$upper.CL),
          p("oranges_trends.csv"))

# Contrast families on a one-way design with an ordered factor.
set.seed(404)
dd <- data.frame(dose = factor(rep(c("d1", "d2", "d3", "d4"), each = 30)))
dd$y <- as.integer(dd$dose) * 0.5 + rnorm(nrow(dd))
wcsv(dd, p("contrast_data.csv"))
fitc <- lm(y ~ dose, data = dd)
emc <- emmeans(fitc, ~ dose)
for (meth in c("poly", "consec", "helmert", "pairwise")) {
  sc <- emm_sum(summary(contrast(emc, method = meth), adjust = "none"))
  wcsv(data.frame(contrast = sc$contrast, estimate = sc$estimate,
                       SE = sc$SE, t = sc$t.ratio, p = sc$p.value),
            p(sprintf("contrast_%s.csv", meth)))
}
cat("SECTION IV done\n")

# ===========================================================================
# SECTION V — Multiplicity adjustments
# ===========================================================================
set.seed(505)
g <- factor(rep(c("ctrl", "t1", "t2", "t3", "t4"), each = 24))
ym <- as.integer(g) * 0.18 + rnorm(length(g))
dm <- data.frame(g = g, y = ym)
wcsv(dm, p("multiplicity_data.csv"))
fitm <- lm(y ~ g, data = dm)
emm_m <- emmeans(fitm, ~ g)
# Pairwise family under several adjustments.
for (adj in c("none", "tukey", "sidak", "holm", "bonferroni", "BH", "scheffe")) {
  sa <- emm_sum(summary(contrast(emm_m, "pairwise"), adjust = adj))
  wcsv(data.frame(contrast = sa$contrast, estimate = sa$estimate,
                       SE = sa$SE, t = sa$t.ratio, p = sa$p.value),
            p(sprintf("mult_pairwise_%s.csv", adj)))
}
# General (rank>1) multivariate-t adjustment over the FULL pairwise family —
# 10 correlated contrasts among 5 means. This is the hard QMC case, distinct
# from the rank-1 Dunnett shared-control special case below; emmeans drives it
# through mvtnorm's randomised QMC, so we seed for a reproducible reference.
set.seed(5150)
smvt <- emm_sum(summary(contrast(emm_m, "pairwise"), adjust = "mvt"))
wcsv(data.frame(contrast = smvt$contrast, estimate = smvt$estimate,
                SE = smvt$SE, t = smvt$t.ratio, p_mvt = smvt$p.value),
     p("mult_pairwise_mvt.csv"))
# Dunnett many-to-one MVT at several k.
for (k in c(3, 5, 8)) {
  levs <- c("ctrl", paste0("t", seq_len(k)))
  set.seed(600 + k)
  gg <- factor(rep(levs, each = 25), levels = levs)
  yy <- as.integer(gg) * 0.15 + rnorm(length(gg))
  dk <- data.frame(g = gg, y = yy)
  wcsv(dk, p(sprintf("dunnett_data_k%d.csv", k)))
  fk <- lm(y ~ g, data = dk)
  sk <- emm_sum(summary(contrast(emmeans(fk, ~ g), "trt.vs.ctrl"),
                        adjust = "mvt"))
  wcsv(data.frame(contrast = sk$contrast, estimate = sk$estimate,
                       SE = sk$SE, t = sk$t.ratio, df = sk$df, p_mvt = sk$p.value),
            p(sprintf("dunnett_k%d.csv", k)))
}

# --- Inference utilities on the same 5-group design: equivalence /
# non-inferiority (test(delta=, side=)) and compact letter display (cld). ---
# Equivalence (TOST), delta = 0.5, two-sided: H0 |theta| >= 0.5 (not equiv)
# vs H1 within +/- 0.5. R triggers TOST automatically when delta > 0.
eqv <- as.data.frame(test(emm_m, delta = 0.5))
wcsv(data.frame(g = eqv$g, p_value = eqv$p.value), p("equiv_emm.csv"))
# Non-inferiority, delta = 0.3, right-sided, on the unadjusted pairwise family.
nin <- as.data.frame(test(contrast(emm_m, "pairwise", adjust = "none"),
                          delta = 0.3, side = ">"))
wcsv(data.frame(contrast = nin$contrast, p_value = nin$p.value),
     p("equiv_noninf.csv"))
# Compact letter display (multcomp::cld), Tukey-adjusted, alpha = 0.05. Only
# emitted if multcomp is installed; otherwise the notebook validates cld() as a
# self-consistency check against the (separately R-validated) Tukey p-values.
if (requireNamespace("multcomp", quietly = TRUE)) {
  cldf <- as.data.frame(multcomp::cld(emm_m, alpha = 0.05, Letters = letters,
                                      adjust = "tukey"))
  cldf$.group <- gsub(" ", "", as.character(cldf$.group))
  wcsv(data.frame(g = cldf$g, group = cldf$.group), p("cld.csv"))
}
cat("SECTION V done\n")

# ===========================================================================
# SECTION VI — Mixed-model df (Satterthwaite / Kenward-Roger / vc_formula)
# ===========================================================================
if (ok_mixed) {
  set.seed(606)
  ns <- 24; nps <- 8
  subj <- factor(rep(seq_len(ns), each = nps))
  trt <- factor(rep_len(c("A", "B"), ns * nps))
  re <- rnorm(ns, sd = 1.2)[as.integer(subj)]
  yv <- 2 + (trt == "B") * 0.8 + re + rnorm(ns * nps, sd = 0.9)
  dmix <- data.frame(subj = subj, trt = trt, y = yv)
  wcsv(dmix, p("mixed_ri_data.csv"))
  m_ri <- lmerTest::lmer(y ~ trt + (1 | subj), data = dmix)
  satt <- emm_sum(emmeans(m_ri, ~ trt, lmer.df = "satterthwaite"))
  wcsv(data.frame(trt = satt$trt, emmean = satt$emmean, SE = satt$SE,
                       df = satt$df), p("mixed_ri_satt.csv"))
  kr <- emm_sum(emmeans(m_ri, ~ trt, lmer.df = "kenward-roger"))
  wcsv(data.frame(trt = kr$trt, emmean = kr$emmean, SE = kr$SE,
                       df = kr$df), p("mixed_ri_kr.csv"))

  # vc_formula via the proven oats fixture (nested Block/Variety variance
  # component). statsmodels MixedLM converges to the same non-boundary
  # solution as lme4 here; an arbitrary synthetic crossed design can collapse
  # one component to the boundary in statsmodels (a known optimiser
  # difference), so we cross-validate on the canonical oats data instead.
  # Matches the Sprint-7.A fixture: a 63-row subset, Block random intercept
  # + Block:Variety variance component.
  oats <- read.csv(p("oats_data.csv"))
  names(oats)[names(oats) == "yield"] <- "yld"
  drop_idx <- c(1, 2, 3, 5, 8, 13, 21, 34, 55)   # R 1-based; Sprint-7.A subset
  oats_sub <- oats[-drop_idx, ]
  oats_sub$BlockVariety <- factor(paste(oats_sub$Block, oats_sub$Variety,
                                        sep = ":"))
  oats_sub$Block <- factor(oats_sub$Block)
  oats_sub$Variety <- factor(oats_sub$Variety)
  oats_sub$nitro <- factor(oats_sub$nitro)
  wcsv(oats_sub, p("oats_vc_data.csv"))
  m_vc <- lmerTest::lmer(
    yld ~ Variety + nitro + (1 | Block) + (1 | BlockVariety), data = oats_sub)
  vkr <- emm_sum(emmeans(m_vc, ~ nitro, lmer.df = "kenward-roger"))
  wcsv(data.frame(nitro = vkr$nitro, emmean = vkr$emmean, SE = vkr$SE,
                       df = vkr$df), p("oats_vc_kr.csv"))
  # lme4's REML variance-component estimates — used by the notebook to
  # demonstrate that the ~4% KR-df gap is a FIT-level difference
  # (statsmodels' REML optimiser lands on slightly different variances)
  # rather than a method-level KR-df bug.
  vcdf <- as.data.frame(VarCorr(m_vc))
  wcsv(data.frame(component = vcdf$grp, variance = vcdf$vcov),
            p("oats_vc_varcomp.csv"))
  # vc_formula NESTED-MODEL F-test reference: KRmodcomp + SATmodcomp on
  # the sub-plot `nitro` fixed effect (4 levels => df_num = 3), with the
  # Block + Block:Variety variance components present. Cross-validates
  # pymmeans's krmodcomp()/satmodcomp() on a variance-component model.
  big_vc <- lmerTest::lmer(
    yld ~ Variety + nitro + (1 | Block) + (1 | BlockVariety), data = oats_sub)
  small_vc <- lmerTest::lmer(
    yld ~ Variety + (1 | Block) + (1 | BlockVariety), data = oats_sub)
  krf <- KRmodcomp(big_vc, small_vc)$test
  satf <- SATmodcomp(big_vc, small_vc)$test
  wcsv(data.frame(
    method   = c("KR", "SAT"),
    stat     = c(as.numeric(krf["Ftest", "stat"]), as.numeric(satf[1, "statistic"])),
    ndf      = c(as.numeric(krf["Ftest", "ndf"]),  as.numeric(satf[1, "ndf"])),
    ddf      = c(as.numeric(krf["Ftest", "ddf"]),  as.numeric(satf[1, "ddf"])),
    p_value  = c(as.numeric(krf["Ftest", "p.value"]), as.numeric(satf[1, "p.value"]))
  ), p("oats_vc_ftest.csv"))
  cat("SECTION VI done\n")
} else {
  cat("SECTION VI skipped (lme4/lmerTest/pbkrtest not available)\n")
}

# ===========================================================================
# SECTION VII — New-feature cross-validation (cov.keep, nesting, submodel)
# ===========================================================================
# cov.keep: keep a few-valued numeric covariate at its unique values.
set.seed(707)
nk <- 240
dk2 <- data.frame(
  g = factor(sample(c("a", "b"), nk, replace = TRUE)),
  dose = sample(c(0, 10, 20), nk, replace = TRUE),
  x = rnorm(nk)
)
dk2$y <- (dk2$g == "b") * 0.6 + 0.05 * dk2$dose + 0.4 * dk2$x +
  rnorm(nk, sd = 0.7)
wcsv(dk2, p("covkeep_data.csv"))
fit_k <- lm(y ~ g * dose + x, data = dk2)
# pymmeans `cov_keep=["dose"]` auto-shows the kept covariate, which equals
# R's `cov.keep` WITH the covariate also placed in specs (~ g * dose). R's
# `cov.keep` with `~ g` alone instead averages over dose. Per-cell numbers
# are identical; we cross-validate the matching call.
sk2 <- emm_sum(emmeans(fit_k, ~ g * dose, cov.keep = "dose"))
wcsv(data.frame(g = sk2$g, dose = sk2$dose, emmean = sk2$emmean,
                     SE = sk2$SE), p("covkeep_emm.csv"))

# submodel = "type2": cross-validate our Type-II marginality.
set.seed(708)
ds <- data.frame(
  A = factor(sample(c("a", "b", "c"), 300, replace = TRUE)),
  B = factor(sample(c("p", "q"), 300, replace = TRUE)),
  x = rnorm(300)
)
ds$y <- (ds$A == "b") * 0.5 + (ds$A == "c") * 1.0 + (ds$B == "q") * 0.3 +
  0.4 * ds$x + rnorm(300, sd = 0.7)
wcsv(ds, p("submodel_data.csv"))
fit_s <- lm(y ~ A * B + x, data = ds)
ss2 <- emm_sum(emmeans(fit_s, ~ A, submodel = "type2"))
wcsv(data.frame(A = ss2$A, emmean = ss2$emmean, SE = ss2$SE),
          p("submodel_type2_emm.csv"))
# R's ACTUAL type2 pairwise contrasts (not differenced EMMs) — the direct
# cross-validation target for pymmeans's submodel='type2' contrasts.
ss2c <- emm_sum(summary(contrast(emmeans(fit_s, ~ A, submodel = "type2"),
                                 "pairwise"), adjust = "none"))
wcsv(data.frame(contrast = ss2c$contrast, estimate = ss2c$estimate,
                     SE = ss2c$SE, t = ss2c$t.ratio, p = ss2c$p.value),
          p("submodel_type2_pairwise.csv"))
# R submodel="minimal" (== "type3"): projection onto the primary-factor-only
# submodel. Its raw EMMs are NOT reference-centered, so they're directly
# comparable (unlike type2). Validate both the minimal and type3 strings.
ssm <- emm_sum(emmeans(fit_s, ~ A, submodel = "minimal"))
wcsv(data.frame(A = ssm$A, emmean = ssm$emmean, SE = ssm$SE),
          p("submodel_minimal_emm.csv"))

# nesting: a genuinely nested design (school within district).
set.seed(709)
distr <- rep(c("d1", "d2", "d3"), each = 4 * 15)
sch <- rep(paste0(rep(c("d1", "d2", "d3"), each = 4), "_s",
                  rep(1:4, times = 3)), each = 15)
yv2 <- as.integer(factor(distr)) * 2 + rnorm(length(distr))
dn <- data.frame(district = factor(distr), school = factor(sch), y = yv2)
wcsv(dn, p("nesting_data.csv"))
fit_n <- lm(y ~ district + school, data = dn)
en <- emmeans(fit_n, ~ district, nesting = list(school = "district"))
sn <- emm_sum(en)
wcsv(data.frame(district = sn$district, emmean = sn$emmean, SE = sn$SE),
          p("nesting_emm.csv"))
cat("SECTION VII done\n")

# ===========================================================================
# SECTION VIII — Weighting sensitivity (unbalanced design)
# ===========================================================================
# On an UNBALANCED design, averaging the nuisance factor with equal vs
# proportional (cell-frequency) weights gives DIFFERENT — both correct —
# EMMs. We cross-validate pymmeans against R under both schemes to show
# the weighting choice is honoured exactly.
set.seed(808)
# B is distributed unevenly WITHIN each A level, so equal != proportional.
mk <- function(a, np_, pq) data.frame(
  A = a, B = sample(c("p", "q"), np_, replace = TRUE, prob = c(pq, 1 - pq)))
sb <- rbind(mk("a", 90, 0.8), mk("b", 50, 0.4), mk("c", 40, 0.5))
sb$A <- factor(sb$A); sb$B <- factor(sb$B)
sb$y <- (sb$A == "b") * 0.5 + (sb$A == "c") * 1.0 + (sb$B == "q") * 0.7 +
  rnorm(nrow(sb), sd = 0.8)
wcsv(sb, p("weights_data.csv"))
fit_w <- lm(y ~ A + B, data = sb)
for (wt in c("equal", "proportional", "cells")) {
  sw <- emm_sum(emmeans(fit_w, ~ A, weights = wt))
  wcsv(data.frame(A = sw$A, emmean = sw$emmean, SE = sw$SE),
            p(sprintf("weights_emm_%s.csv", wt)))
}
# --- VIII.b: nuisance × weights interaction. A 3-factor unbalanced design
# (g target × b nuisance × c remaining non-target) lets `nuisance='b'` flip
# *only* the b-dimension to equal-marginal averaging while c retains the
# requested weighting scheme. R's `wt.nuis='equal'` (the default in
# `ref_grid(..., nuisance=)`) is the semantic pymmeans now matches under
# weights='outer' and weights='proportional'.
set.seed(2024)
n_nw <- 240
g_nw <- factor(sample(c("g1","g2","g3"), n_nw, replace = TRUE, prob = c(.5,.3,.2)))
b_nw <- factor(sample(c("bL","bH"),       n_nw, replace = TRUE, prob = c(.8,.2)))
c_nw <- factor(sample(c("cA","cB","cC"),  n_nw, replace = TRUE, prob = c(.6,.3,.1)))
y_nw <- (g_nw=="g2")*0.4 + (g_nw=="g3")*1.0 + (b_nw=="bH")*0.7 +
        (c_nw=="cB")*0.5 + (c_nw=="cC")*1.0 + rnorm(n_nw, sd=0.7)
nw_data <- data.frame(g=g_nw, b=b_nw, c=c_nw, y=y_nw)
wcsv(nw_data, p("nuisance_data.csv"))
m_nw <- lm(y ~ g + b + c, data=nw_data)
nw_cases <- list(
  list(label="prop_no_nuis",  call=function() emmeans(m_nw, ~ g, weights="proportional")),
  list(label="prop_nuis_b",   call=function() emmeans(m_nw, ~ g, weights="proportional", nuisance="b", wt.nuis="equal")),
  list(label="prop_nuis_bc",  call=function() emmeans(m_nw, ~ g, weights="proportional", nuisance=c("b","c"), wt.nuis="equal")),
  list(label="outer_nuis_b",  call=function() emmeans(m_nw, ~ g, weights="outer",         nuisance="b", wt.nuis="equal"))
)
for (cs in nw_cases) {
  s <- as.data.frame(summary(cs$call()))
  wcsv(data.frame(g=s$g, emmean=s$emmean, SE=s$SE),
       p(sprintf("nuisance_%s_emm.csv", cs$label)))
}
# Cells × nuisance reference: the analytical-extrapolation path that
# pymmeans now matches. R `wt.nuis='equal'` handles empty
# (target, nuisance, non-nuisance) sub-cells via the linear model's
# analytical prediction; pymmeans bridges via patsy.build_design_matrices
# at each grid combo.
cells_cases <- list(
  list(label="cells_nuis_b",   call=function() emmeans(m_nw, ~ g, weights="cells", nuisance="b",       wt.nuis="equal")),
  list(label="cells_nuis_bc",  call=function() emmeans(m_nw, ~ g, weights="cells", nuisance=c("b","c"), wt.nuis="equal"))
)
for (cs in cells_cases) {
  s <- as.data.frame(summary(cs$call()))
  wcsv(data.frame(g=s$g, emmean=s$emmean, SE=s$SE),
       p(sprintf("nuisance_%s_emm.csv", cs$label)))
}
cat("SECTION VIII done\n")

# ===========================================================================
# SECTION IX — Cox proportional hazards (survival::coxph)
# ===========================================================================
# The Cox partial likelihood does not identify the baseline hazard, so the
# link-scale EMM is a RELATIVE log-hazard; the identifiable, scale-invariant
# quantity is the log-hazard-RATIO contrast (pairs). We cross-validate those
# against R survival::coxph + emmeans. (ordinal / multinomial / survey
# references are the committed test-suite cross-validations in
# ../../tests/r_reference, copied into cs_ref/.)
if (requireNamespace("survival", quietly = TRUE)) {
  library(survival)
  set.seed(909)
  ncx <- 200
  dcx <- data.frame(g = factor(sample(c("a", "b", "c"), ncx, replace = TRUE)),
                    x = rnorm(ncx))
  lp <- (dcx$g == "b") * 0.5 + (dcx$g == "c") * 1.0 + 0.3 * dcx$x
  dcx$time <- rexp(ncx, rate = exp(lp))
  dcx$status <- rbinom(ncx, 1, 0.8)
  wcsv(dcx, p("cox_data.csv"))
  cfit <- coxph(Surv(time, status) ~ g + x, data = dcx)
  cct <- as.data.frame(summary(contrast(emmeans(cfit, ~ g), "pairwise"),
                               adjust = "none"))
  wcsv(data.frame(contrast = cct$contrast, estimate = cct$estimate,
                       SE = cct$SE, p = cct$p.value),
            p("cox_pairs.csv"))
  # IX.b: STRATIFIED Cox. `strata(site)` lets each site carry its own
  # baseline hazard h_{0,s}(t); the linear-predictor coefficients (and
  # hence the log-hazard-ratio EMM contrasts) come from the stratified
  # partial likelihood. pymmeans handles this transparently because
  # statsmodels PHReg(strata=) exposes the same params / vcov shape.
  set.seed(909 + 1); n_s <- 400
  d_s <- data.frame(
    g    = factor(sample(c("gA","gB","gC"), n_s, replace = TRUE)),
    x    = rnorm(n_s),
    site = factor(sample(c("s1","s2","s3"), n_s, replace = TRUE))
  )
  lp_s <- (d_s$g == "gB") * 0.5 + (d_s$g == "gC") * 1.0 + 0.3 * d_s$x
  d_s$T      <- rexp(n_s, rate = exp(lp_s))
  d_s$status <- rbinom(n_s, 1, 0.8)
  wcsv(d_s, p("cox_strata_data.csv"))
  fit_s <- coxph(Surv(T, status) ~ g + x + strata(site), data = d_s)
  cct_s <- as.data.frame(summary(contrast(emmeans(fit_s, ~ g), "pairwise"),
                                 adjust = "none"))
  wcsv(data.frame(contrast = cct_s$contrast, estimate = cct_s$estimate,
                  SE = cct_s$SE, p = cct_s$p.value),
       p("cox_strata_pairs.csv"))
  # IX.c: Weibull AFT (parametric survival, R survreg). The linear
  # predictor lives on the log-time scale: log T = X β + σ ε. R's
  # survreg(dist="weibull") and lifelines WeibullAFTFitter use the same
  # AFT parameterisation so β agrees to optimiser precision, and the
  # pymmeans EMM machinery (driven by from_aft → ModelInfo) reproduces
  # emmeans(survreg, ...) at the same ~1e-6 solver tolerance.
  set.seed(42); n_a <- 300
  g_a <- factor(sample(c("gA","gB","gC"), n_a, replace = TRUE))
  x_a <- rnorm(n_a)
  lp_a <- (g_a == "gB") * 0.5 + (g_a == "gC") * 1.0 + 0.3 * x_a
  T_a <- exp(lp_a + 0.5 * rnorm(n_a))
  E_a <- rbinom(n_a, 1, 0.85)
  d_a <- data.frame(g = g_a, x = x_a, T = T_a, E = E_a)
  wcsv(d_a, p("aft_data.csv"))
  fit_a <- survreg(Surv(T, E) ~ g + x, data = d_a, dist = "weibull")
  em_a <- emmeans(fit_a, ~ g)
  sa <- as.data.frame(summary(em_a))
  wcsv(data.frame(g = sa$g, emmean = sa$emmean, SE = sa$SE, df = sa$df),
       p("aft_emm.csv"))
  ct_a <- as.data.frame(summary(contrast(em_a, "pairwise", adjust = "none")))
  wcsv(data.frame(contrast = ct_a$contrast, estimate = ct_a$estimate,
                  SE = ct_a$SE, df = ct_a$df, p_value = ct_a$p.value),
       p("aft_pairs.csv"))
  # Additional AFT distributions (lognormal, loglogistic) on the same
  # seeded fixture. lifelines uses different params_ block names per
  # distribution (mu_ / alpha_ / lambda_); the pymmeans `from_aft`
  # adapter detects the location block by matching patsy design columns.
  for (dist in c("lognormal", "loglogistic")) {
    fit_d <- survreg(Surv(T, E) ~ g + x, data = d_a, dist = dist)
    ct_d <- as.data.frame(summary(contrast(emmeans(fit_d, ~ g),
                                           "pairwise", adjust = "none")))
    wcsv(data.frame(contrast = ct_d$contrast, estimate = ct_d$estimate,
                    SE = ct_d$SE, df = ct_d$df, p_value = ct_d$p.value),
         p(sprintf("aft_pairs_%s.csv", dist)))
  }
  # IX.d: Cox PH with Gaussian frailty (random hazard effect on a
  # clustering id). R `coxph(... + frailty(id, "gaussian"))` uses
  # Laplace approximation; pymmeans bridges this via a PyMC Cox-
  # partial-likelihood + Gaussian-frailty model + `posterior_emmeans`
  # — validated in the notebook (§XII.3) at convergence accuracy.
  set.seed(99); n_cl_f <- 12; n_per_f <- 18; n_f <- n_cl_f * n_per_f
  id_f <- factor(rep(seq_len(n_cl_f), each = n_per_f))
  g_f  <- factor(sample(c("gA","gB","gC"), n_f, replace = TRUE))
  x_f  <- rnorm(n_f)
  u_f  <- rnorm(n_cl_f, sd = 0.4)
  lp_f <- (g_f == "gB") * 0.5 + (g_f == "gC") * 1.0 + 0.3 * x_f +
          u_f[as.integer(id_f)]
  d_f  <- data.frame(
    id = id_f, g = g_f, x = x_f,
    status = rbinom(n_f, 1, 0.8),
    T = rexp(n_f, rate = exp(lp_f))
  )
  wcsv(d_f, p("cox_frailty_data.csv"))
  fit_f <- coxph(Surv(T, status) ~ g + x + frailty(id, distribution = "gaussian"),
                 data = d_f)
  ct_f <- as.data.frame(summary(contrast(emmeans(fit_f, ~ g),
                                         "pairwise", adjust = "none")))
  wcsv(data.frame(contrast = ct_f$contrast, estimate = ct_f$estimate,
                  SE = ct_f$SE),
       p("cox_frailty_pairs.csv"))
  # Capture R's MLE: β coefs + Laplace frailty variance (no SE for the
  # frailty variance in R's standard output — Bayesian posterior gives
  # a credible interval instead).
  bf <- coef(fit_f)
  wcsv(data.frame(
    quantity = c(names(bf), "sigma_sq_frailty"),
    value    = c(unname(bf), fit_f$history$frailty$theta)
  ), p("cox_frailty_R.csv"))
  # IX.e: Cox PH with GAMMA frailty (the other R-supported distribution).
  # Parametrisation: u ~ Gamma(1/theta, 1/theta) so E[u]=1, Var[u]=theta.
  fit_fg <- coxph(Surv(T, status) ~ g + x +
                  frailty(id, distribution = "gamma"), data = d_f)
  ct_fg <- as.data.frame(summary(contrast(emmeans(fit_fg, ~ g),
                                          "pairwise", adjust = "none")))
  wcsv(data.frame(contrast = ct_fg$contrast, estimate = ct_fg$estimate,
                  SE = ct_fg$SE),
       p("cox_gamma_frailty_pairs.csv"))
  # IX.f: Generalized-Gamma AFT — survreg doesn't expose this dist, so R's
  # reference is flexsurvreg (which R emmeans does not directly support).
  # Capture the β coefs only; the pymmeans contract is "lifelines β
  # matches R flexsurv β to ~1e-6 (the Weibull / LogN / LogLog optimiser
  # tolerance), and from_aft + emmeans then build the EMM via the same
  # Lβ algebra validated for the other AFT distributions in §XI".
  if (requireNamespace("flexsurv", quietly = TRUE)) {
    library(flexsurv)
    fit_gg <- flexsurvreg(Surv(T, E) ~ g + x, data = d_a, dist = "gengamma")
    cf <- coef(fit_gg)
    # The covariate block (mu + ggB + ggC + x) — exclude scale/shape (sigma, Q).
    cv_names <- c("mu", "ggB", "ggC", "x")
    wcsv(data.frame(coef = cv_names, value = unname(cf[cv_names])),
         p("aft_gengamma_R.csv"))
  }
  cat("SECTION IX (Cox + strata + AFT + Gaussian/Gamma frailty + gengamma) done\n")
} else {
  cat("SECTION IX (Cox) skipped — survival not available\n")
}

# ---------------------------------------------------------------------------
# IX.g: one-way repeated-measures fixture for the AnovaRM equivalence demo.
# In R `aov(y ~ cond + Error(subj/cond)) + emmeans` is IDENTICAL to
# `lmer(y ~ cond + (1|subj)) + emmeans` for the means; pymmeans bridges via
# statsmodels MixedLM (which matches lmer to optimiser precision).
# ---------------------------------------------------------------------------
set.seed(31); n_s_rm <- 24
conds_rm <- c("c1", "c2", "c3")
n_rm <- n_s_rm * length(conds_rm)
subj_rm <- factor(rep(seq_len(n_s_rm), each = length(conds_rm)))
cond_rm <- factor(rep(conds_rm, n_s_rm), levels = conds_rm)
ranef_rm <- rnorm(n_s_rm, sd = 0.7)
y_rm <- 1.0 + (cond_rm == "c2") * 0.4 + (cond_rm == "c3") * 1.0 +
        ranef_rm[as.integer(subj_rm)] + rnorm(n_rm, sd = 0.5)
d_rm <- data.frame(subj = subj_rm, cond = cond_rm, y = y_rm)
wcsv(d_rm, p("rm_data.csv"))
if (ok_mixed) {
  fit_rm <- lmerTest::lmer(y ~ cond + (1 | subj), data = d_rm)
  em_rm <- as.data.frame(summary(emmeans(fit_rm, ~ cond)))
  wcsv(data.frame(cond = em_rm$cond, emmean = em_rm$emmean,
                  SE = em_rm$SE, df = em_rm$df),
       p("rm_lmer_emm.csv"))
  cat("IX.g (AnovaRM / lmer equivalence) done\n")
}

# ---------------------------------------------------------------------------
# IX.h: multivariate-GLM fixture (the brms / mvregrid surrogate).
# Two independent Poisson responses sharing the same design — `brms` would
# fit this jointly via Stan; the Python equivalent is a PyMC joint
# Poisson model + `posterior_emm_summary`. The R reference is the
# per-response Poisson GLM (which equals the brms/joint-likelihood result
# when the response components are conditionally independent).
# ---------------------------------------------------------------------------
set.seed(55); n_mp <- 240
g_mp <- factor(sample(c("gA","gB","gC"), n_mp, replace = TRUE))
x_mp <- rnorm(n_mp)
lp1 <- 1.0 + (g_mp=="gB")*0.4 + (g_mp=="gC")*0.9 + 0.2*x_mp
lp2 <- 0.5 + (g_mp=="gB")*0.3 + (g_mp=="gC")*1.1 + 0.4*x_mp
d_mp <- data.frame(
  g = g_mp, x = x_mp,
  y1 = rpois(n_mp, lambda = exp(lp1)),
  y2 = rpois(n_mp, lambda = exp(lp2))
)
wcsv(d_mp, p("mv_pois_data.csv"))
fit1 <- glm(y1 ~ g + x, data = d_mp, family = poisson())
fit2 <- glm(y2 ~ g + x, data = d_mp, family = poisson())
em1 <- as.data.frame(summary(emmeans(fit1, ~ g)))
em2 <- as.data.frame(summary(emmeans(fit2, ~ g)))
wcsv(data.frame(g = em1$g, emmean = em1$emmean, SE = em1$SE),
     p("mv_pois_y1_emm.csv"))
wcsv(data.frame(g = em2$g, emmean = em2$emmean, SE = em2$SE),
     p("mv_pois_y2_emm.csv"))
cat("IX.h (multivariate Poisson GLM via per-response GLMs) done\n")

# ===========================================================================
# SECTION X — Multivariate-response OLS + mvcontrast (the "mlm" path)
# ===========================================================================
# R `emmeans` on a multivariate `lm` (`cbind(y1,y2,y3) ~ ...`) introduces a
# `rep.meas` pseudo-factor (one level per response column) and offers
# `mvcontrast` for Hotelling-T² / F-tests across responses. pymmeans's
# matching surface is `multivariate_emmeans` + `mvcontrast`.
set.seed(1010)
n_mv <- 60
g_mv <- factor(sample(c("a", "b", "c"), n_mv, replace = TRUE))
x_mv <- rnorm(n_mv)
beta_mv <- c(a = 0, b = 0.5, c = 1)
y1 <- beta_mv[as.character(g_mv)] + 0.3 * x_mv + rnorm(n_mv, sd = 0.5)
y2 <- 0.7 * beta_mv[as.character(g_mv)]      + rnorm(n_mv, sd = 0.5)
y3 <- 0.4 * beta_mv[as.character(g_mv)] + 0.2 * x_mv + rnorm(n_mv, sd = 0.5)
mv_data <- data.frame(g = g_mv, x = x_mv, y1 = y1, y2 = y2, y3 = y3)
wcsv(mv_data, p("mv_data.csv"))
mv_fit <- lm(cbind(y1, y2, y3) ~ g + x, data = mv_data)
em_mv <- as.data.frame(emmeans(mv_fit, ~ g | rep.meas))
wcsv(data.frame(
  g       = em_mv$g,
  rep_meas = em_mv$rep.meas,
  emmean  = em_mv$emmean, SE = em_mv$SE, df = em_mv$df,
  lower_cl = em_mv$lower.CL, upper_cl = em_mv$upper.CL
), p("mv_emm.csv"))
mvc <- as.data.frame(mvcontrast(
  emmeans(mv_fit, ~ g, by = "rep.meas"), "pairwise", mult.name = "rep.meas"
))
wcsv(data.frame(
  contrast = mvc$contrast, T_square = mvc$T.square,
  df1 = mvc$df1, df2 = mvc$df2, F_ratio = mvc$F.ratio, p_value = mvc$p.value
), p("mv_mvc.csv"))
cat("SECTION X (multivariate / mvcontrast) done\n")

cat("\nAll case-study references generated.\n")
