"""Tests for ``pymmeans.ordinal``.

cumulative-link ordinal regression EMMs
(``statsmodels.OrderedModel``). Validated against R
``ordinal::clm`` + ``emmeans`` on a synthetic 3-category dataset.
"""

from __future__ import annotations

import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest


def _fit_ordinal() -> tuple:
    """Load the R-reference dataset and fit statsmodels OrderedModel.

    The data is generated by the R script
    ``tests/r_reference/ordinal_reference.R`` and committed as
    ``ordinal_data.csv`` so the tests work without requiring R.
    Both R and pymmeans should fit identical coefficients (modulo
    optimizer noise ~1e-6) on this CSV.
    """
    from statsmodels.miscmodels.ordinal_model import OrderedModel

    data_csv = Path("tests/r_reference/ordinal_data.csv")
    if not data_csv.exists():
        pytest.skip(
            "Run tests/r_reference/ordinal_reference.R first to "
            "generate ordinal_data.csv and the R reference outputs."
        )
    dat = pd.read_csv(data_csv)
    dat["y"] = dat["y"].astype("category").cat.reorder_categories(
        [0, 1, 2], ordered=True
    )
    dat["g"] = pd.Categorical(dat["g"], categories=["a", "b", "c"])
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        fit = OrderedModel.from_formula(
            "y ~ x1 + g", dat, distr="logit"
        ).fit(method="bfgs", disp=False)
    return fit, dat


def test_ordered_model_no_longer_refused():
    """OrderedModel was previously refused with a
    ``NotImplementedError`` (introduced the refusal,
    lifts it). Verify the standard ``emmeans`` entry
    point now accepts an ordinal fit and returns the latent
    linear-predictor EMM."""
    from pymmeans import emmeans

    fit, _ = _fit_ordinal()
    em = emmeans(fit, "g")
    # Latent EMM should have one row per g level.
    assert len(em.frame) == 3
    assert set(em.frame["g"]) == {"a", "b", "c"}


def test_ordinal_prob_mode_matches_r_emmeans():
    """per-category probability EMMs must match
    R ``emmeans(clm_fit, ~ y | g, mode="prob")`` at
    ``atol=1e-5`` (the residual differences are optimizer noise
    between R's `clm` and statsmodels' BFGS — the underlying
    coefficient estimates already differ at ~1e-6 level)."""
    from pymmeans import ordinal_emmeans

    fit, _ = _fit_ordinal()
    res = ordinal_emmeans(fit, "g", mode="prob")
    ref_csv = Path("tests/r_reference/ordinal_emm_prob.csv")
    if not ref_csv.exists():
        pytest.skip("R reference missing; run ordinal_reference.R")
    ref = pd.read_csv(ref_csv)
    # Align ordering — both should be (a × 3, b × 3, c × 3).
    assert list(res.frame["g"]) == list(ref["g"].astype(str))
    np.testing.assert_allclose(
        res.frame["emmean"].to_numpy(),
        ref["prob"].to_numpy(),
        atol=1e-5,
        err_msg=(
            "pymmeans ordinal prob-mode EMMs must "
            "match R emmeans at atol=1e-5."
        ),
    )
    np.testing.assert_allclose(
        res.frame["SE"].to_numpy(),
        ref["SE"].to_numpy(),
        atol=1e-5,
        err_msg=(
            "pymmeans ordinal prob-mode SEs must "
            "match R emmeans at atol=1e-5."
        ),
    )


def test_ordinal_cumprob_mode_matches_r_emmeans():
    """Cumulative-probability mode parity vs R."""
    from pymmeans import ordinal_emmeans

    fit, _ = _fit_ordinal()
    res = ordinal_emmeans(fit, "g", mode="cum.prob")
    ref_csv = Path("tests/r_reference/ordinal_emm_cumprob.csv")
    if not ref_csv.exists():
        pytest.skip("R reference missing; run ordinal_reference.R")
    ref = pd.read_csv(ref_csv)
    np.testing.assert_allclose(
        res.frame["emmean"].to_numpy(),
        ref["cum.prob"].to_numpy(),
        atol=1e-5,
    )
    np.testing.assert_allclose(
        res.frame["SE"].to_numpy(),
        ref["SE"].to_numpy(),
        atol=1e-5,
    )


def test_ordinal_meanclass_mode_matches_r_emmeans():
    """Expected-category mode parity vs R. Pymmeans uses the
    R-emmeans 1-indexed rank convention so the values match
    directly (no constant offset)."""
    from pymmeans import ordinal_emmeans

    fit, _ = _fit_ordinal()
    res = ordinal_emmeans(fit, "g", mode="mean.class")
    ref_csv = Path("tests/r_reference/ordinal_emm_meanclass.csv")
    if not ref_csv.exists():
        pytest.skip("R reference missing; run ordinal_reference.R")
    ref = pd.read_csv(ref_csv)
    np.testing.assert_allclose(
        res.frame["emmean"].to_numpy(),
        ref["mean.class"].to_numpy(),
        atol=1e-5,
    )
    np.testing.assert_allclose(
        res.frame["SE"].to_numpy(),
        ref["SE"].to_numpy(),
        atol=1e-5,
    )


def test_ordinal_prob_probabilities_sum_to_one():
    """Sanity check: per-cell probabilities must sum to 1.0 ±
    floating-point noise. Catches sign or off-by-one bugs in
    the threshold parameterisation."""
    from pymmeans import ordinal_emmeans

    fit, _ = _fit_ordinal()
    res = ordinal_emmeans(fit, "g", mode="prob")
    per_cell_sum = res.frame.groupby("g", observed=True)["emmean"].sum()
    np.testing.assert_allclose(per_cell_sum.to_numpy(), 1.0, atol=1e-12)


def test_ordinal_exc_prob_equals_one_minus_cum_prob():
    """``mode="exc.prob"`` must return ``1 - mode="cum.prob"``."""
    from pymmeans import ordinal_emmeans

    fit, _ = _fit_ordinal()
    cum = ordinal_emmeans(fit, "g", mode="cum.prob").frame
    exc = ordinal_emmeans(fit, "g", mode="exc.prob").frame
    np.testing.assert_allclose(
        exc["emmean"].to_numpy(),
        1.0 - cum["emmean"].to_numpy(),
        atol=1e-12,
    )


def test_ordinal_mode_latent_delegates_to_emmeans():
    """``mode="latent"`` is a no-op wrapper that just calls
    :func:`emmeans` — verify the latent EMM frame is identical."""
    from pymmeans import emmeans, ordinal_emmeans

    fit, _ = _fit_ordinal()
    em1 = emmeans(fit, "g")
    em2 = ordinal_emmeans(fit, "g", mode="latent")
    pd.testing.assert_frame_equal(em1.frame, em2.frame)


def test_ordinal_mode_invalid_raises():
    """Unknown ``mode`` strings must raise ``ValueError``."""
    from pymmeans import ordinal_emmeans

    fit, _ = _fit_ordinal()
    with pytest.raises(ValueError, match="unknown mode"):
        ordinal_emmeans(fit, "g", mode="bogus_mode")


def test_refuses_unknown_distr_with_qdrg_hint():
    """previously, the cloglog branch hand-coded
    the Gumbel-min CDF. But scipy.stats.gumbel_r is Gumbel-MAX
    (a different sign convention), so passing it to statsmodels'
    OrderedModel and then to pymmeans would silently produce
    wrong SEs. Now, anything other than 'logit' / 'probit'
    is refused with a clear error pointing at ``qdrg`` as the
    workaround.

    Guard: the error message must mention 'qdrg' so the user
    knows where to go for cloglog / other links."""
    from pymmeans.ordinal import _link_cdf_pdf

    with pytest.raises(NotImplementedError, match="qdrg"):
        _link_cdf_pdf("cloglog")
    with pytest.raises(NotImplementedError, match="qdrg"):
        _link_cdf_pdf("gumbel_r")


def test_link_detection_by_name_not_substring():
    """previously, used substring matching on
    the scipy distribution class name ('logistic' in name.lower())
    which would silently break under a future scipy rename.
    Now uses the stable ``.name`` attribute identity.

    Guard: the link detection finds 'logit' for scipy.stats.logistic
    and 'probit' for scipy.stats.norm, and refuses for any other
    distribution."""
    from scipy import stats

    from pymmeans.ordinal import _link_cdf_pdf

    # Smoke test the two supported links via the public _link_cdf_pdf
    # entry; the actual identity check lives inside
    # _extract_ordinal_state but is covered transitively by the
    # R-parity tests above. Note: scipy bound methods don't
    # preserve identity across accesses (``stats.logistic.cdf is
    # stats.logistic.cdf`` returns False), so we compare *values*
    # rather than the function references.
    cdf_logit, _ = _link_cdf_pdf("logit")
    cdf_probit, _ = _link_cdf_pdf("probit")
    x = np.array([-1.0, 0.0, 1.0])
    np.testing.assert_allclose(cdf_logit(x), stats.logistic.cdf(x), atol=1e-15)
    np.testing.assert_allclose(cdf_probit(x), stats.norm.cdf(x), atol=1e-15)
